import Head from "next/head";
import AppFooter from "../components/AppFooter";
import AppHeader from "../components/AppHeader";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import requests from "../utilities/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-700">
        {/* Header */}
        <AppHeader />

        {/* Navbar */}
        <Navbar />

        {/* Results: Movies */}
        <Results results={results} />

        <AppFooter />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre || "fetchTrending";
  const request = await fetch(
    `https://api.themoviedb.org/3${requests[genre].url}`
  ).then((res) => {
    return res.json();
  });

  return {
    props: {
      results: request.results,
    },
  };
}
